#compartment_id              = "ocid1.compartment.oc1..aaaaaaaa..."
compute_shape               = "VM.Standard.A1.Flex"
compute_name                = "lab"
#compute_subnet_id           = "ocid1.subnet.oc1.uk-london-1.aaaaaaaa..."
#compute_image_id            = "ocid1.image.oc1.uk-london-1.aaaaaaaa..."
compute_ssh_authorized_keys = "/home/vagrant/.oci/oci_api_key_public.pem"